// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://savhgzroqgprvcbynksb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNhdmhnenJvcWdwcnZjYnlua3NiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI2NjIxMTcsImV4cCI6MjA2ODIzODExN30.vDxdhud_ktJfYfjz7m7l2sOFJl5tWRLV53p4fMw0F5c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});